apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: materialticket
  labels:
    app: db
spec:
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None   # headless — StatefulSet gets stable DNS: db.materialticket.svc.cluster.local
