name: Docker Compose Build & Deploy to homelab

on:
  push:
    branches:
      - main  # This triggers the workflow only on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop and remove containers (if running)
        run: docker compose down

      - name: Build and start containers
        run: docker compose up -d --build  # Rebuild and start all services

      - name: Verify running containers
        run: docker ps